home/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('',views.product_list_view,name='list'), 
    path('create/',views.product_create_view,name='create'), 
    path('<slug:handle>/',views.product_detail_view,name='detail'), 
    path('<slug:handle>/manage/',views.product_manage_detail_view,name='manage'), 
    path('<slug:handle>/download/<int:pk>/',views.product_attachment_download_view,name='download'), 
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('products/',include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
import pathlib
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.urls import reverse

PROTECTED_MEDIA_ROOT = settings.PROTECTED_MEDIA_ROOT
protected_storage = FileSystemStorage(str(PROTECTED_MEDIA_ROOT))

class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    image = models.ImageField(upload_to="products/", blank=True, null=True)
    name = models.CharField(max_length=120)
    desc = models.CharField(max_length=1000, null=True, blank=True)
    handle = models.SlugField(unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    og_price = models.DecimalField(max_digits=10, decimal_places=2,  default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"handle":self.handle})
    
    def get_manage_url(self):
        return reverse("products:manage", kwargs={"handle":self.handle})
    
def handle_product_attachment_upload(instance, filename):
    return f"products/{instance.product.handle}/attachments/{filename}"
    
class ProductAttachment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, blank=True, null=True)
    file = models.FileField(upload_to=handle_product_attachment_upload, storage=protected_storage)
    isFree = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self,*args,**kwargs):
        if not self.name:
            self.name = pathlib.Path(self.file.name).name
        super().save(*args,**kwargs)

    @property
    def display_name(self):
        return self.name or self.file.name
    
    def get_download_url(self):
        return reverse("products:download", kwargs={"handle":self.product.handle, "pk":self.pk})
    
 

home/forms.py
from django import forms
from .models import Product, ProductAttachment
from django.forms import modelformset_factory, inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


input_css_class = 'form-control'

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name','handle','price']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']=input_css_class

class ProductUpdateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['image','name', 'handle','price']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class']=input_css_class

class ProductAttachmentForm(forms.ModelForm):
    class Meta:
        model = ProductAttachment
        fields = ['file','name', 'isFree','active']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            if field in ['isFree','active']:
                continue
            self.fields[field].widget.attrs['class']=input_css_class

ProductAttachmentModelFormSet = modelformset_factory(
    ProductAttachment,
    form = ProductAttachmentForm,
    fields = ['file','name', 'isFree','active'],
    extra=0,
    can_delete=True
)

ProductAttachmentInlineFormSet = inlineformset_factory(
    Product,
    ProductAttachment,
    form = ProductAttachmentForm,
    formset=ProductAttachmentModelFormSet,
    fields = ['file','name', 'isFree','active'],
    extra=0,
    can_delete=True
)

home/views.py
import mimetypes
from django.http import FileResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProductForm, ProductUpdateForm,ProductAttachmentInlineFormSet
from .models import Product, ProductAttachment
from django.contrib.auth.models import User

def product_create_view(request):
    context={}
    form = ProductForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        if request.user.is_authenticated:
            obj.user = request.user
            obj.save()
            return redirect(obj.get_manage_url())
    context['form']=form
    return render(request,'products/create.html',context)

def product_list_view(request):
    object_list = Product.objects.all()
    context={
        "object_list":object_list,
        "user":request.user
    }
    return render(request,'products/list.html',context)

def product_manage_detail_view(request, handle=None):
    obj = get_object_or_404(Product, handle=handle)
    attachments = ProductAttachment.objects.filter(product=obj)
    is_manager = False
    if request.user.is_authenticated:
        is_manager = obj.user == request.user
    context = {"object": obj}
    if not is_manager:
        return HttpResponseBadRequest()
    form = ProductUpdateForm(request.POST or None, request.FILES or None, instance=obj)
    formset = ProductAttachmentInlineFormSet(request.POST or None, 
                                             request.FILES or None,queryset=attachments)
    if form.is_valid() and formset.is_valid():
        instance = form.save(commit=False)
        instance.save()
        formset.save(commit=False)
        for _form in formset:
            is_delete = _form.cleaned_data.get("DELETE")
            try:
                attachment_obj = _form.save(commit=False)
            except:
                attachment_obj = None
            if is_delete:
                if attachment_obj is not None:
                    if attachment_obj.pk:
                        attachment_obj.delete()
            else:
                if attachment_obj is not None:
                    attachment_obj.product  = instance
                    attachment_obj.save()
        return redirect(obj.get_manage_url())
    context['form'] = form
    context['formset'] = formset
    return render(request, 'products/manage.html', context)

def product_detail_view(request, handle=None):
    object = get_object_or_404(Product, handle=handle)
    attachments = ProductAttachment.objects.filter(product=object)
    is_owner=False
    if request.user.is_authenticated:
        is_owner = True
    context={"object":object, "is_owner":is_owner,"attachments":attachments}
    return render(request,'products/detail.html',context)


def product_attachment_download_view(request, handle=None, pk=None):
    attachment = get_object_or_404(ProductAttachment, product__handle=handle, pk=pk)
    # attachment = ProductAttachment.objects.all().first()
    can_download = attachment.isFree 
    if request.user.is_authenticated:
        can_download=True
    if can_download is False:
        return HttpResponseBadRequest() 
    file = attachment.file.open(mode='rb')
    filename = attachment.file.name
    content_type, _ = mimetypes.guess_type(filename)
    response = FileResponse(file)
    response['Content-Type'] = content_type or 'application/octet-stream'
    response['Content-Disposition']=f'attachment;filename={filename}'
    return response

main/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html',{})

templates/base.html
<!-- templates/_base.html -->

{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ArtStellars</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

</head>

<body class="">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>

    <div class="container">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="text-2xl content-center flex flex-row mt-52 font-bold	">
    <div class="w-full ml-8">
        <img src="https://i.ibb.co/ydTX0hL/logo.jpg" class="" alt="logo">
    </div>
    <div class="w-full pt-32">
        <p>
            Discover digital masterpieces on our platform. 
        </p>  
        <p>
            Elevate your space with unique, captivating art. 
        </p>
        <p>
            Browse,buy,and own exceptional digital creations today!
        </p>  
    </div>
</div>

{% endblock %}

templates/navbar.html
<nav class=" border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <div class="flex flex-row">
      <a href="{% url 'home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
        <a href="{% url 'home' %}"><img src="https://i.ibb.co/ydTX0hL/logo.jpg" class="h-8 mr-4" alt="logo"></a>      
        <a href="{% url 'home' %}">
          <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">ArtStellar</span>
        </a>
      </a>
    </div>
  <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0">
    
      <li>
        <a href="{% url 'home' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Home</a>
      </li>
      <li>
        <a href="{% url 'products:list' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Products</a>
      </li>
      <li>
        <a href="{% url 'products:create' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Create</a>
      </li>
    </ul>
  </div>
  </div>
</nav>

templates/products/attach.html
{% if attachments.exists %}
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Name
                </th>
                <th scope="col" class="px-6 py-3">
                    
                </th>
                <th scope="col" class="px-6 py-3">
                    Download
                </th>
            </tr>
        </thead>
        <tbody>
            {% for attach in attachments %}
            <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{attach.name}}
                </th>
                <td class="px-6 py-4">
                    {% if attach.isFree %}Free Download{% endif %}
                </td>
                <td class="px-6 py-4">
                    {% if is_owner or attach.isFree %}
                    <a href="{{attach.get_download_url}}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Download</a>
                    {% else %}
                    <p>Purchase to download</p>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

templates/products/create.html
{% extends "base.html" %}
{% block content %}

<form method="POST" action="." class="form-control">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn-submit mt-4">Submit</button>
</form>

{% endblock %}

templates/products/detail.html
{% extends "base.html" %}
{% block content %}

<div class="flex flex-row ml-12 mr-10 mt-24">
    <div class="w-3/4 mr-8">
        <h2 class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl dark:text-white">{{object.name}}</h2>
        <p class="mb-3 text-gray-500 dark:text-gray-400">{{object.desc}}</p>
        {% include 'products/attach.html' with attachments=attachments is_owner=is_owner %}
    </div>
    <div class="w-1/4 mr-8">
        {% if is_owner %}
        <p></p>
        {% else %}
        <div>
            <div>
                <span class="text-3xl font-semibold">$</span>
                <span class="text-5xl font-extrabold tracking-tight">49</span>
            </div>
            <button type="submit" class="btn-submit mt-4">Buy Now</button>
        </div>
        {% endif %}
        <div>
            <div class="grid gap-4">
                {% if object.image %}
                <div>
                    <img class="h-auto max-w-full rounded-lg" src="{{object.image.url}}" alt="">
                </div>
                {% endif %}
            </div>
        </div>
        <div>
            {% if form %}
                <form method="POST" action="." class="form-control">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn-submit mt-4">Submit</button>
                </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/products/list-card.html
<div class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 ml-10">
    {% if product.image %}
        <a href="{{product.get_absolute_url}}">
            <img class="p-8 rounded-t-lg" src="{{product.image.url}}" alt="{{product.name}}" />
        </a>
    {% endif %}
    <div class="px-5 pb-5">
        <a href="{{product.get_absolute_url}}">
            <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white">{{product.name}}</h5>
        </a>

        <div class="flex items-center justify-between">
            <span class="text-3xl font-bold text-gray-900 dark:text-white">₹{{product.price}}</span>
            <a href="{{product.get_absolute_url}}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">See More</a>
        </div>
    </div>
</div>

templates/products/list.html
{% extends "base.html" %}

{% block content %}


<h1 class="mb-4 text-center text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Pixels whisper tales on a digital canvas</h1>
<p class="mb-6 text-center text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">Explore our curated collection of digital artworks. From vibrant paintings to intricate designs, find the perfect piece to enhance your surroundings.</p>



<div class="grid content-center grid-cols-2 md:grid-cols-3 gap-4 ml-10">
    {% for obj in object_list %}
        {% include 'products/list-card.html' with product=obj %}
    {% endfor %}
</div>

{% endblock %}

templates/products/manage.html
{% extends "base.html" %}


{% block content %}

<form  class='space-y-5' method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div>
    {{ form.as_p }}
    </div>

    <div>
        {{ formset.management_form }}
        <div class="pb-3 border-b space-y-3" id="attachments">
            {% for form in formset %}
            <div>
                {{ form.as_p }}
            </div>
            {% endfor %}
        </div>
    </div>

    <button class="btn-submit mt-2" id="add-attachment-btn">Add attachment</button>

    <button type="submit" class="btn-submit mt-2">Save</button>
</form>



<div class="hidden" id="blank-form">
    {{ formset.empty_form }}
</div>

<script>
   const blankFormEl = document.querySelector("#blank-form")
   const attachmentContainer = document.querySelector("#attachments")
   const addAttachmentBtn = document.querySelector("#add-attachment-btn")
   const managementFormInputEl = document.querySelector("#id_form-TOTAL_FORMS")
   addAttachmentBtn.addEventListener("click", handleAttachmentBtnClick)
    function cloneBlankForm(){
        if (blankFormEl) {
            const newBlankForm = blankFormEl.cloneNode(true)
            const totalFormValue = parseInt(managementFormInputEl.value)
            var formRegex = new RegExp(`__prefix__`, 'g');
            newBlankForm.innerHTML = newBlankForm.innerHTML.replace(formRegex, totalFormValue)
            managementFormInputEl.value = totalFormValue + 1
            newBlankForm.classList.add("attachment-form")
            newBlankForm.classList.remove("hidden")
            newBlankForm.removeAttribute("id")
            // console.log(newBlankForm)
            return newBlankForm
        }
    }

    function handleAttachmentBtnClick(event) {
        if (event){
            event.preventDefault()
        }
        const newForm = cloneBlankForm()
        attachmentContainer.appendChild(newForm)
    }

</script>


{% endblock %}